# Generated by Django 3.2.6 on 2021-08-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                (
                    'artist_id',
                    models.CharField(
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ('followers', models.IntegerField()),
                ('href', models.URLField()),
                ('name', models.CharField(max_length=255)),
                ('popularity', models.IntegerField()),
                ('artist_type', models.CharField(max_length=255)),
                ('uri', models.URLField()),
                ('genres', models.ManyToManyField(to='api.Genre')),
            ],
            options={
                'verbose_name': 'artist',
                'verbose_name_plural': 'artists',
                'db_table': 'artist',
            },
        ),
    ]
