# Generated by Django 3.2.6 on 2021-08-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_market'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('artist_id', models.CharField(max_length=22, primary_key=True, serialize=False, unique=True)),
                ('album_type', models.CharField(max_length=50)),
                ('href', models.URLField()),
                ('name', models.CharField(max_length=150)),
                ('release_date', models.DateField()),
                ('last_checked_date', models.DateField()),
                ('release_date_precision', models.CharField(max_length=10)),
                ('total_tracks', models.IntegerField()),
                ('other_album_type', models.CharField(max_length=50)),
                ('uri', models.URLField()),
                ('available_markets', models.ManyToManyField(blank=True, db_table='available_markets', related_name='album', to='api.Market')),
            ],
            options={
                'verbose_name': 'album',
                'verbose_name_plural': 'albums',
                'db_table': 'album',
            },
        ),
    ]
