# Generated by Django 3.2.6 on 2021-08-10 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistExternalURL',
            fields=[
                ('external_url_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.artist')),
            ],
            options={
                'verbose_name': 'artist external url',
                'verbose_name_plural': 'artist external urls',
                'db_table': 'artist_external_url',
            },
        ),
    ]
