# Generated by Django 3.2.6 on 2021-08-10 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_artistexternalurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumExternalURL',
            fields=[
                ('external_url_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.album')),
            ],
            options={
                'verbose_name': 'album external url',
                'verbose_name_plural': 'album external urls',
                'db_table': 'album_external_url',
            },
        ),
    ]
