# Generated by Django 3.2.6 on 2021-08-10 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_albumexternalurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistImageURL',
            fields=[
                ('image_url_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('url', models.URLField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.artist')),
            ],
            options={
                'verbose_name': 'artist image url',
                'verbose_name_plural': 'artist image urls',
                'db_table': 'artist_image_url',
            },
        ),
    ]
