# Generated by Django 3.2.6 on 2021-08-10 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_artistimageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumImageURL',
            fields=[
                ('image_url_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('url', models.URLField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.album')),
            ],
            options={
                'verbose_name': 'album image url',
                'verbose_name_plural': 'album image urls',
                'db_table': 'album_image_url',
            },
        ),
    ]
