# Generated by Django 3.2.6 on 2021-08-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_albumimageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(blank=True, db_table='artists', related_name='album', to='api.Artist'),
        ),
    ]
