# Generated by Django 3.2.6 on 2021-08-12 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_album_artists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist_id',
            new_name='album_id',
        ),
    ]
