# Generated by Django 3.2.6 on 2021-08-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_artist_id_album_album_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(blank=True, db_table='artists_albums', related_name='album', to='api.Artist'),
        ),
    ]
