# Generated by Django 3.2.6 on 2021-08-12 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_album_artists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='other_album_type',
            new_name='object_type',
        ),
        migrations.RemoveField(
            model_name='album',
            name='total_tracks',
        ),
    ]
