# Generated by Django 3.2.6 on 2021-08-12 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210812_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='coutry_code',
            new_name='country_code',
        ),
    ]
